### ISSUE TITLE
Turn timeout parameter into options object

### ISSUE THREAD

**Issue by Krinkle** [PixelsCommander/requestIdleCallback-polyfill#1]
The spec has changed recently, the second parameter is now expected to be an object. The implementation in Chrome has been updated to no longer support a number as second parameter.

https://w3c.github.io/requestidlecallback/#window_extensions

e.g. `requestIdleCallback( Function, { timeout: Number } );`.

**Comment by PixelsCommander** [comment]
Done, npm major version bumped to avoid compatibility issues
